# Generated by Django 3.0.8 on 2020-07-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0002_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
